services:
  - type: web
    name: careflow-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: API_VERSION
        value: 1.0.0
      - key: DATABASE_URL
        fromDatabase:
          name: careflow-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: careflow-redis
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: WORKER_API_KEY
        generateValue: true
      - key: CORS_ORIGIN
        value: https://careflow-frontend.onrender.com
      - key: AUTO_MIGRATE
        value: true
      - key: RATE_LIMIT_WINDOW
        value: 15
      - key: RATE_LIMIT_MAX
        value: 100
      - key: CSRF_SECRET
        generateValue: true
      - key: UPLOAD_DIR
        value: uploads
      - key: MAX_FILE_SIZE
        value: 5242880
      - key: SENTRY_DSN
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        sync: false
      - key: S3_BUCKET
        sync: false
    healthCheckPath: /health
    autoDeploy: true
    disk:
      name: uploads
      mountPath: /app/uploads
      sizeGB: 10
    scaling:
      minInstances: 1
      maxInstances: 3
      targetMemoryPercent: 80
      targetCPUPercent: 80
    buildFilter:
      paths:
        - package.json
        - package-lock.json
        - src/**
        - migrations/**
        - uploads/**
        - .env.example
        - render.yaml

databases:
  - name: careflow-db
    databaseName: careflow
    user: careflow
    plan: free
    ipAllowList: []
    region: oregon 