services:
  - type: web
    name: careflow-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: API_VERSION
        value: 1.0.0
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://careflow-frontend.onrender.com
      - key: AUTO_MIGRATE
        value: true
      - key: RATE_LIMIT_WINDOW
        value: 15
      - key: RATE_LIMIT_MAX
        value: 100
      - key: CSRF_SECRET
        generateValue: true
      - key: UPLOAD_DIR
        value: uploads
      - key: MAX_FILE_SIZE
        value: 5242880
    healthCheckPath: /api/health
    autoDeploy: true
    disk:
      name: uploads
      mountPath: /app/uploads
      sizeGB: 10
    buildFilter:
      paths:
        - package.json
        - package-lock.json
        - src/**
        - migrations/**
        - uploads/**
        - .env.example
        - render.yaml 